# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import animeengineservice_pb2 as animeengineservice__pb2


class AnimeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetReviews = channel.unary_unary(
        '/Anime/GetReviews',
        request_serializer=animeengineservice__pb2.GetReviewsRequest.SerializeToString,
        response_deserializer=animeengineservice__pb2.GetReviewsResponse.FromString,
        )


class AnimeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetReviews(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AnimeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetReviews': grpc.unary_unary_rpc_method_handler(
          servicer.GetReviews,
          request_deserializer=animeengineservice__pb2.GetReviewsRequest.FromString,
          response_serializer=animeengineservice__pb2.GetReviewsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Anime', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
