# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animeengineservice.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='animeengineservice.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x18\x61nimeengineservice.proto\"\"\n\x11GetReviewsRequest\x12\r\n\x05limit\x18\x01 \x02(\x05\"t\n\x12GetReviewsResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.GetReviewsResponse.Review\x1a\x31\n\x06Review\x12\r\n\x05score\x18\x01 \x02(\x05\x12\x0b\n\x03uid\x18\x02 \x02(\x05\x12\x0b\n\x03mid\x18\x03 \x02(\x05\x32@\n\x05\x41nime\x12\x37\n\nGetReviews\x12\x12.GetReviewsRequest\x1a\x13.GetReviewsResponse\"\x00'
)




_GETREVIEWSREQUEST = _descriptor.Descriptor(
  name='GetReviewsRequest',
  full_name='GetReviewsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='GetReviewsRequest.limit', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=62,
)


_GETREVIEWSRESPONSE_REVIEW = _descriptor.Descriptor(
  name='Review',
  full_name='GetReviewsResponse.Review',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='GetReviewsResponse.Review.score', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='GetReviewsResponse.Review.uid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mid', full_name='GetReviewsResponse.Review.mid', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=180,
)

_GETREVIEWSRESPONSE = _descriptor.Descriptor(
  name='GetReviewsResponse',
  full_name='GetReviewsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='GetReviewsResponse.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETREVIEWSRESPONSE_REVIEW, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=180,
)

_GETREVIEWSRESPONSE_REVIEW.containing_type = _GETREVIEWSRESPONSE
_GETREVIEWSRESPONSE.fields_by_name['results'].message_type = _GETREVIEWSRESPONSE_REVIEW
DESCRIPTOR.message_types_by_name['GetReviewsRequest'] = _GETREVIEWSREQUEST
DESCRIPTOR.message_types_by_name['GetReviewsResponse'] = _GETREVIEWSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetReviewsRequest = _reflection.GeneratedProtocolMessageType('GetReviewsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREVIEWSREQUEST,
  '__module__' : 'animeengineservice_pb2'
  # @@protoc_insertion_point(class_scope:GetReviewsRequest)
  })
_sym_db.RegisterMessage(GetReviewsRequest)

GetReviewsResponse = _reflection.GeneratedProtocolMessageType('GetReviewsResponse', (_message.Message,), {

  'Review' : _reflection.GeneratedProtocolMessageType('Review', (_message.Message,), {
    'DESCRIPTOR' : _GETREVIEWSRESPONSE_REVIEW,
    '__module__' : 'animeengineservice_pb2'
    # @@protoc_insertion_point(class_scope:GetReviewsResponse.Review)
    })
  ,
  'DESCRIPTOR' : _GETREVIEWSRESPONSE,
  '__module__' : 'animeengineservice_pb2'
  # @@protoc_insertion_point(class_scope:GetReviewsResponse)
  })
_sym_db.RegisterMessage(GetReviewsResponse)
_sym_db.RegisterMessage(GetReviewsResponse.Review)



_ANIME = _descriptor.ServiceDescriptor(
  name='Anime',
  full_name='Anime',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=182,
  serialized_end=246,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetReviews',
    full_name='Anime.GetReviews',
    index=0,
    containing_service=None,
    input_type=_GETREVIEWSREQUEST,
    output_type=_GETREVIEWSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANIME)

DESCRIPTOR.services_by_name['Anime'] = _ANIME

# @@protoc_insertion_point(module_scope)
